# Generated by Selenium IDE
import pytest
import time
import json
from datetime import datetime
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys




class TestTesteDiaHora():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testeDiaHora(self):
    now = datetime.now()
    ano = now.year
    mes = now.month
    dia = now.day
    hora = now.hour
    minuto = now.minute
    num2 = "1"
    hora_adiantada = int(hora) + int(num2)

    # Test name: Teste_Dia _Hora
    # Step # | name | target | value | comment
    # 1 | open | https://docs.google.com/forms/d/e/1FAIpQLSfWfPcADbvEPrGDePWhY-agioR1TAyFZTW-hwNTucN28-VACg/viewform |  | #
    self.driver.get("https://docs.google.com/forms/d/e/1FAIpQLSfWfPcADbvEPrGDePWhY-agioR1TAyFZTW-hwNTucN28-VACg/viewform")
    # 2 | setWindowSize | 1144x915 |  | 
    self.driver.set_window_size(1144, 915)
    # 64 | storeValue | css=.freebirdFormviewerViewItemsDateDateInputs .quantumWizTextinputPaperinputInput | 'dia' | #
    self.vars["'\'(str(dia))'\'"] = self.driver.find_element(By.CSS_SELECTOR, ".freebirdFormviewerViewItemsDateDateInputs .quantumWizTextinputPaperinputInput").get_attribute(str(dia))
    # 65 | storeValue | css=.freebirdFormviewerViewItemsDateDateInputs .quantumWizTextinputPaperinputInput | 'mes' | #
    self.vars["\'(str(mes))\'"] = self.driver.find_element(By.CSS_SELECTOR, ".freebirdFormviewerViewItemsDateDateInputs .quantumWizTextinputPaperinputInput").get_attribute(str(mes))
    # 66 | storeValue | css=.freebirdFormviewerViewItemsDateDateInputs .quantumWizTextinputPaperinputInput | 'ano' | #
    self.vars["\'(str(ano))\'"] = self.driver.find_element(By.CSS_SELECTOR, ".freebirdFormviewerViewItemsDateDateInputs .quantumWizTextinputPaperinputInput").get_attribute(str(ano))
    # 67 | echo | $dia/$mes/$ano |  | #
    print( str(dia) + '/' + str(mes) + '/'+ str(ano))
    # 69 | echo | css=.freebirdFormviewerViewItemsTimeNumberEdit:nth-child(1) .quantumWizTextinputPaperinputInput | 00 | #
    print(str("css=.freebirdFormviewerViewItemsTimeNumberEdit:nth-child(1) .quantumWizTextinputPaperinputInput"))
    # 70 | click | css=.freebirdFormviewerViewItemsTimeNumberEdit:nth-child(3) .quantumWizTextinputPaperinputInput |  | #
    self.driver.find_element(By.CSS_SELECTOR, ".freebirdFormviewerViewItemsTimeNumberEdit:nth-child(3) .quantumWizTextinputPaperinputInput").send_keys(str(hora))
    # 71 | type | css=.freebirdFormviewerViewItemsTimeNumberEdit:nth-child(3) .quantumWizTextinputPaperinputInput | 58 | #
    self.driver.find_element(By.CSS_SELECTOR, ".freebirdFormviewerViewItemsTimeNumberEdit:nth-child(3) .quantumWizTextinputPaperinputInput").send_keys(str(minuto))
    # 72 | click | css=.quantumWizButtonPaperbuttonLabel |  | #
    self.driver.find_element(By.CSS_SELECTOR, ".quantumWizButtonPaperbuttonLabel").click()